productpage:
  replicaCount: 3
  image:
    repository: istio/examples-bookinfo-productpage
    tag: 1.16.2-prod

details:
  replicaCount: 3
  image:
    repository: istio/examples-bookinfo-details
    tag: 1.16.2-prod

reviews:
  replicaCount: 3
  image:
    repository: istio/examples-bookinfo-reviews
    tag: 1.16.2-prod

ratings:
  replicaCount: 3
  image:
    repository: istio/examples-bookinfo-ratings
    tag: 1.16.2-prod

service:
  name: bookinfo-prod
  port: 9080
  targetPort: 9080