apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookinfo-staging
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/my-janala/argocd-app-of-apps.git
  destinations:
    - namespace: bookinfo-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'