apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/namespace: bookinfo-prod
spec:
  project: bookinfo-prod
  source:
    repoURL: https://github.com/my-janala/argocd-app-of-apps.git
    targetRevision: main
    path: helm-charts/bookinfo/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true