apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: {{ .Release.Namespace }}
  labels:
    app: bookinfo
    service: details
spec:
  replicas: {{ .Values.details.replicaCount }}
  selector:
    matchLabels:
      app: bookinfo
      service: details
  template:
    metadata:
      labels:
        app: bookinfo
        service: details
    spec:
      containers:
      - name: details
        image: {{ .Values.details.image.repository }}:{{ .Values.details.image.tag }}
        ports:
        - containerPort: 9080