apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: bookinfo
    service: reviews
spec:
  replicas: {{ .Values.reviews.replicaCount }}
  selector:
    matchLabels:
      app: bookinfo
      service: reviews
  template:
    metadata:
      labels:
        app: bookinfo
        service: reviews
    spec:
      containers:
      - name: reviews
        image: {{ .Values.reviews.image.repository }}:{{ .Values.reviews.image.tag }}
        ports:
        - containerPort: 9080