apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-dev
  namespace: argocd
spec:
  project: bookinfo-dev
  source:
    repoURL: https://github.com/my-janala/argocd-app-of-apps.git
    targetRevision: HEAD
    path: helm-charts/bookinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-dev
  helm:
    parameters:
      - name: productpage.replicaCount
        value: "1"
      - name: details.replicaCount
        value: "1"
      - name: reviews.replicaCount
        value: "1"
      - name: ratings.replicaCount
        value: "1"