apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/namespace: bookinfo-dev
spec:
  project: bookinfo-dev
  source:
    repoURL: https://github.com/my-janala/argocd-app-of-apps.git
    targetRevision: main
    path: helm-charts/bookinfo/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true